name: likeminds_feed_ss_fl
description: A new Flutter package project.
version: 2.0.0
publish_to: none
homepage: "https://likeminds.community/"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <=3.16.9"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^3.0.6
  likeminds_feed_flutter_core: 1.0.2
  likeminds_feed: 1.7.1

  media_kit: ^1.1.10 # Primary package.
  media_kit_video: ^1.2.4 # For video rendering.
  media_kit_libs_video: ^1.0.4

dependency_override:
  sliver_tools: 0.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/likeminds_feed_ss_fl/assets/icons/document.svg
    - packages/likeminds_feed_ss_fl/assets/icons/gallery.svg
    - packages/likeminds_feed_ss_fl/assets/icons/poll.svg
    - packages/likeminds_feed_ss_fl/assets/icons/video.svg
    - packages/likeminds_feed_ss_fl/assets/icons/pin.svg
    - packages/likeminds_feed_ss_fl/assets/icons/like.svg
    - packages/likeminds_feed_ss_fl/assets/icons/comment.svg
    - packages/likeminds_feed_ss_fl/assets/icons/share.svg
    - packages/likeminds_feed_ss_fl/assets/icons/like_filled.svg
    - packages/likeminds_feed_ss_fl/assets/icons/pdf.svg
    - packages/likeminds_feed_ss_fl/assets/icons/chat_lines.svg
    - packages/likeminds_feed_ss_fl/assets/icons/mistery-box.svg
